/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.teacake.monolith;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int buttonnextlevel=0x7f050000;
        public static final int buttonpreviouslevel=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int m_game=0x7f040005;
        public static final int m_m_new=0x7f040007;
        public static final int m_m_options=0x7f040006;
        public static final int s_classic=0x7f04000a;
        public static final int s_dizzy=0x7f04000b;
        public static final int s_dizzy_monolith=0x7f04000d;
        public static final int s_energy=0x7f040004;
        public static final int s_game_over=0x7f04000e;
        public static final int s_level=0x7f040002;
        public static final int s_lines=0x7f040003;
        public static final int s_monolith=0x7f04000c;
        public static final int s_next_game_mode=0x7f04000f;
        public static final int s_next_level=0x7f040008;
        public static final int s_previous_game_mode=0x7f040010;
        public static final int s_previous_level=0x7f040009;
        public static final int s_score=0x7f040001;
    }
}
